version: '3.8'
services:
    db:
        image: postgres
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: files
        volumes:
            - data:/var/lib/postgresql/data
    tika:
        image: apache/tika:latest-full
        ports:
            - ${TIKA_PORT}:9998
